trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '160de157-172e-4e27-b957-bc1bd0ab751b'
  imageRepository: 'app1nginx'
  containerRegistry: 'aksdevopapp1.azurecr.io'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
      displayName: 'Checkout main branch'

    # Checkout the master branch to get the Dockerfile
    - checkout: self
      displayName: 'Checkout master branch'
      persistCredentials: true
      clean: true
      fetchDepth: 0
      submodules: true
      path: master

    - script: |
        echo "Contents of the Dockerfile from master branch:"
        cat master/Dockerfile
      displayName: 'Print Dockerfile from master branch'

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/master/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
