# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: 'Checkout main branch'

# Fetch Dockerfile from master branch
- checkout: 
    repository: self
    ref: refs/heads/master
    path: master
  displayName: 'Checkout master branch for Dockerfile'

# Print Dockerfile for verification
- script: |
    echo "Contents of the Dockerfile from master branch:"
    cat master/Dockerfile
  displayName: 'Print Dockerfile from master branch'

# Build Docker image
- task: Docker@2
  inputs:
    command: build
    Dockerfile: '$(Build.SourcesDirectory)/master/Dockerfile'
    containerRegistry: 'yourContainerRegistry'
    repository: 'yourRepository'
    tags: 'latest'




